site_name: Orbit Platform Documentation
site_url: https://magistravsh.github.io/OrbitDocs/
theme:
  name: material
  icon:
    logo: material/orbit
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tracking
  font:
    code: JetBrains Mono
    text: Inter
  palette:
    primary: white
plugins:
  - search
  - awesome-pages
