site_name: Orbit Platform Documentation
site_url: https://magistravsh.github.io/OrbitDocs
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  font:
    code: JetBrains Mono
    text: Inter
  palette:
    primary: white
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
