site_name: Orbit Platform Documentation
site_url: https://docs.portalapp.games/
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/Pictogrammers-Material-Orbit.512.png
  icon:
    logo: material/orbit
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.code.select
  font:
    code: JetBrains Mono
    text: Inter
  palette:
    primary: white
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
     