site_name: Orbit Platform Documentation
site_url: https://mydomain.org/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tracking
  font:
    code: JetBrains Mono
    text: Inter
  palette:
    primary: white
plugins:
  - search