name: Deploy MkDocs

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      - name: Деплой на GitHub Pages
        run: mkdocs gh-deploy --force
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
